#!/bin/sh
set -e

echo "==> DevNS.me Certificate Setup"
echo ""

# Create directories if they don't exist
mkdir -p /etc/ssl/traefik
mkdir -p /etc/traefik

cd /etc/ssl/traefik

# Download all certificates based on environment variables
echo "==> Scanning for certificate URLs..."
i=1
cert_count=0

while true; do
  cert_var="HTTPS_CERT_URL_$i"
  key_var="HTTPS_KEY_URL_$i"

  # Use eval to get the value of the variable
  cert_url=$(eval echo \$$cert_var)
  key_url=$(eval echo \$$key_var)

  # Break if either URL is empty
  if [ -z "$cert_url" ] || [ -z "$key_url" ]; then
    break
  fi

  echo "==> Downloading certificate pair $i..."
  echo "    Certificate: $cert_url"
  echo "    Private Key: $key_url"

  # Download certificate and key
  if wget -q "$cert_url" -O "certificate$i.crt" && wget -q "$key_url" -O "private$i.key"; then
    echo "    ✓ Successfully downloaded certificate $i"
    cert_count=$((cert_count + 1))
  else
    echo "    ✗ Failed to download certificate $i"
    # Remove partial files
    rm -f "certificate$i.crt" "private$i.key"
  fi

  echo ""
  i=$((i + 1))
done

echo "==> Downloaded $cert_count certificate pair(s)"
echo ""

# Generate tls.yml file
echo "==> Generating /etc/traefik/tls.yml..."

cat > /etc/traefik/tls.yml << 'EOF'
# DevNS.me - HTTPS Certificates Configuration
# This file is auto-generated by traefik-https-helper container
# Do not edit manually - changes will be overwritten on container restart

tls:
  certificates:
EOF

# Add all downloaded certificates to tls.yml
i=1
while [ -f "/etc/ssl/traefik/certificate$i.crt" ] && [ -f "/etc/ssl/traefik/private$i.key" ]; do
  cat >> /etc/traefik/tls.yml << EOF
    - certFile: /etc/ssl/traefik/certificate$i.crt
      keyFile: /etc/ssl/traefik/private$i.key
EOF
  i=$((i + 1))
done

if [ $cert_count -eq 0 ]; then
  echo "    ⚠ No certificates configured"
  echo "    Add HTTPS_CERT_URL_1 and HTTPS_KEY_URL_1 to .env to enable HTTPS"
else
  echo "    ✓ Added $cert_count certificate(s) to tls.yml"
fi

echo ""
echo "==> Certificate setup complete!"
echo ""
echo "TLS configuration:"
cat /etc/traefik/tls.yml

exit 0
